name: Fork Repositories

on:
  workflow_dispatch: # Allows manual trigger
  schedule: # Runs daily at midnight
    - cron: '0 0 * * *'

jobs:
  fork-repos:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Authenticate GitHub CLI
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: gh auth login --with-token $GITHUB_TOKEN

    - name: List repositories
      run: gh repo list azure --json name --jq '.[] | select(.name | startswith("terraform-avm-")) | .name' > repos.txt

    - name: Fork or update repositories
      run: |
        while read repo; do
          if gh repo view ${{ github.repository_owner }}/$repo > /dev/null 2>&1; then
            echo "Repository $repo already exists in the organization. Updating..."
            git clone https://github.com/${{ github.repository_owner }}/$repo
            cd $repo
            git remote add upstream https://github.com/azure/$repo
            git fetch upstream
            git checkout main
            git merge upstream/main
            git push origin main
            cd ..
          else
            gh repo fork azure/$repo --org ${{ github.repository_owner }} --remote=false
          fi
        done < repos.txt