name: Update Terraform Modules List

on:
  workflow_dispatch:  # This allows manual triggering
  schedule:
    - cron: '0 0 * * 1'  # Run every Monday at midnight UTC

jobs:
  update-modules:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup GitHub CLI
      uses: cli/cli@v2

    - name: Fetch Terraform repositories and update modules.yml
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        cat << EOF > update_modules.sh
        #!/bin/bash

        fetch_all_repos() {
            local page=1
            while true; do
                local batch=\$(gh api -H "Accept: application/vnd.github+json" "/orgs/Azure/repos?per_page=100&page=\$page" \
                    --jq '.[].name')
                if [ -z "\$batch" ]; then
                    break
                fi
                echo "\$batch"
                ((page++))
            done
        }

        # Fetch all repositories
        all_repos=\$(fetch_all_repos)

        # Search for Terraform-related repositories
        terraform_repos=\$(echo "\$all_repos" | grep -i "terraform-avm")

        # Update modules.yml file
        echo "modules:" > config/modules.yml
        echo "\$terraform_repos" | while read repo; do
          echo "  - name: \$repo" >> config/modules.yml
          echo "    source: Azure/\$repo" >> config/modules.yml
        done

        # Print summary
        echo "Updated config/modules.yml with the following repositories:"
        cat config/modules.yml
        EOF

        chmod +x update_modules.sh
        ./update_modules.sh

    - name: Commit and push if changes
      run: |
        git config --global user.name 'GitHub Action'
        git config --global user.email 'action@github.com'
        git add config/modules.yml
        git diff --quiet && git diff --staged --quiet || (git commit -m "Update Terraform modules list" && git push)